name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

  workflow_dispatch: # Allows manual execution

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Generate Snake Animation
      uses: Platane/snk@v3
      with:
        github_user_name: SaiUday999
        outputs: github-snake.svg

    - name: Commit and Push to Output Branch
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Generate GitHub contribution snake"
        git push origin output
